name: Terraform EKS CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
      

jobs:

  #########################################
  # VERSIONING JOB
  #########################################

  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Read & Increment Version
        id: bump
        run: |
          FILE="version.txt"

          if [ ! -f $FILE ]; then
            echo "v1.0.0" > $FILE
          fi

          VERSION=$(cat $FILE)

          echo "Current version: $VERSION"

          MAJOR=$(echo $VERSION | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # CHANGE LOGIC HERE
          # patch bump (default)
          PATCH=$((PATCH+1))

          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"

          echo "New version: $NEW_VERSION"

          echo $NEW_VERSION > $FILE

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit Updated Version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Auto bump version to ${{ steps.bump.outputs.version }}"
          git push

  #########################################
  # TERRAFORM DEPLOY
  #########################################

  deploy:
    needs: versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::088310115913:role/OpenID-Connect

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: pillars/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: pillars/dev
        run: |
          terraform plan \
          -var="app_version=${{ needs.versioning.outputs.version }}"

      - name: Terraform Apply
        working-directory: pillars/dev
        run: |
          terraform apply -auto-approve \
          -var="app_version=${{ needs.versioning.outputs.version }}"
